"""
GitHub Issue Adapter for iam-issue Agent

Maps IssueSpec contracts to GitHub issue payloads for future
creation via API. Currently generates drafts only (no creation).
"""

import sys
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime

# Add parent directory for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from shared_contracts import IssueSpec, Severity, IssueType


def get_severity_labels(severity: Severity) -> List[str]:
    """
    Map IssueSpec severity to GitHub labels.

    Args:
        severity: Severity enum value

    Returns:
        List of label names
    """
    severity_map = {
        Severity.CRITICAL: ["severity: critical", "priority: urgent"],
        Severity.HIGH: ["severity: high", "priority: high"],
        Severity.MEDIUM: ["severity: medium", "priority: normal"],
        Severity.LOW: ["severity: low", "priority: low"],
        Severity.INFO: ["info", "documentation"]
    }
    return severity_map.get(severity, ["severity: unknown"])


def get_issue_type_labels(issue_type: IssueType) -> List[str]:
    """
    Map IssueSpec type to GitHub labels.

    Args:
        issue_type: IssueType enum value

    Returns:
        List of label names
    """
    type_map = {
        IssueType.ADK_VIOLATION: ["adk", "compliance", "bug"],
        IssueType.PATTERN_DRIFT: ["adk", "pattern", "technical-debt"],
        IssueType.SECURITY: ["security", "vulnerability"],
        IssueType.PERFORMANCE: ["performance", "optimization"],
        IssueType.TECH_DEBT: ["technical-debt", "refactor"],
        IssueType.MISSING_DOC: ["documentation", "enhancement"],
        IssueType.CONFIG_ERROR: ["configuration", "bug"]
    }
    return type_map.get(issue_type, ["enhancement"])


def format_issue_body(issue: IssueSpec) -> str:
    """
    Format IssueSpec into GitHub issue body with structured template.

    Args:
        issue: IssueSpec object

    Returns:
        Formatted markdown body
    """
    body_parts = []

    # Header with metadata
    body_parts.append(f"## {issue.title}\n")

    # Summary section
    body_parts.append("### Summary\n")
    body_parts.append(f"{issue.description}\n")

    # Location information
    if issue.file_path:
        body_parts.append("### Location\n")
        body_parts.append(f"**File:** `{issue.file_path}`\n")
        if issue.line_start:
            if issue.line_end:
                body_parts.append(f"**Lines:** {issue.line_start}-{issue.line_end}\n")
            else:
                body_parts.append(f"**Line:** {issue.line_start}\n")

    # Pattern violation details
    if issue.pattern_violated or issue.expected_pattern:
        body_parts.append("### Pattern Details\n")
        if issue.pattern_violated:
            body_parts.append(f"**Violated Pattern:** {issue.pattern_violated}\n")
        if issue.expected_pattern:
            body_parts.append(f"**Expected Pattern:** {issue.expected_pattern}\n")

    # Metadata
    body_parts.append("### Metadata\n")
    body_parts.append(f"- **Issue ID:** `{issue.id}`\n")
    body_parts.append(f"- **Type:** {issue.type.value}\n")
    body_parts.append(f"- **Severity:** {issue.severity.value}\n")
    body_parts.append(f"- **Detected By:** {issue.detected_by}\n")
    body_parts.append(f"- **Created:** {issue.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n")

    if issue.tags:
        body_parts.append(f"- **Tags:** {', '.join(issue.tags)}\n")

    # Footer
    body_parts.append("\n---\n")
    body_parts.append("*This issue was generated by the IAM SWE Pipeline*\n")
    body_parts.append(f"*Agent: {issue.detected_by}*\n")

    return "\n".join(body_parts)


def issue_spec_to_github_payload(
    issue: IssueSpec,
    assignees: Optional[List[str]] = None,
    milestone: Optional[int] = None
) -> Dict[str, Any]:
    """
    Convert IssueSpec to GitHub issue API payload.

    Args:
        issue: IssueSpec object
        assignees: Optional list of GitHub usernames to assign
        milestone: Optional milestone number

    Returns:
        Dictionary matching GitHub Issues API format
    """
    # Combine labels from severity, type, and tags
    labels = []
    labels.extend(get_severity_labels(issue.severity))
    labels.extend(get_issue_type_labels(issue.type))

    # Add custom tags as labels
    if issue.tags:
        labels.extend(issue.tags)

    # Remove duplicates and empty labels
    labels = list(set(l for l in labels if l))

    # Build payload
    payload = {
        "title": issue.title,
        "body": format_issue_body(issue),
        "labels": labels
    }

    # Optional fields
    if assignees:
        payload["assignees"] = assignees

    if milestone:
        payload["milestone"] = milestone

    return payload


def batch_issue_specs_to_payloads(
    issues: List[IssueSpec],
    assignees: Optional[List[str]] = None,
    milestone: Optional[int] = None
) -> List[Dict[str, Any]]:
    """
    Convert multiple IssueSpecs to GitHub issue payloads.

    Args:
        issues: List of IssueSpec objects
        assignees: Optional assignees for all issues
        milestone: Optional milestone for all issues

    Returns:
        List of GitHub issue payloads
    """
    return [
        issue_spec_to_github_payload(issue, assignees, milestone)
        for issue in issues
    ]


def preview_issue_payload(payload: Dict[str, Any]) -> str:
    """
    Format issue payload for human-readable preview.

    Args:
        payload: GitHub issue payload

    Returns:
        Formatted preview string
    """
    lines = []
    lines.append("=" * 60)
    lines.append(f"Title: {payload['title']}")
    lines.append(f"Labels: {', '.join(payload['labels'])}")

    if 'assignees' in payload:
        lines.append(f"Assignees: {', '.join(payload['assignees'])}")

    if 'milestone' in payload:
        lines.append(f"Milestone: #{payload['milestone']}")

    lines.append("-" * 60)
    lines.append(payload['body'])
    lines.append("=" * 60)

    return "\n".join(lines)


# Example usage
if __name__ == "__main__":
    from shared_contracts import create_mock_issue

    print("🎯 GitHub Issue Adapter Demo")
    print("=" * 60)

    # Create mock issue
    issue = create_mock_issue(IssueType.ADK_VIOLATION)

    # Convert to GitHub payload
    payload = issue_spec_to_github_payload(
        issue,
        assignees=["jeremylongshore"],
        milestone=1
    )

    # Preview
    print("\nGenerated GitHub Issue Payload:")
    print(preview_issue_payload(payload))

    # Show raw JSON
    print("\nRaw JSON Payload:")
    import json
    print(json.dumps(payload, indent=2))