#!/usr/bin/env python3
"""
YouTube Scraper - What it does and how it works
"""

print("🎥 YOUTUBE TRANSCRIPT SCRAPER - HOW IT WORKS")
print("=" * 60)
print()
print("📝 WHAT WE SCRAPE:")
print("   • Closed captions/subtitles from videos")
print("   • Auto-generated OR manual captions")
print("   • Full text of everything said in the video")
print()
print("🎯 YOUR CHANNELS CONFIGURED:")
print()
print("1. Pine Hollow Auto Diagnostics")
print("   Example content we'd extract:")
print("   'So we have a 2018 Ford F-150 with a P0171 and P0174")
print("   system too lean codes on both banks. First thing I'm")
print("   going to do is check fuel trims with my scan tool...")
print()
print("2. Scanner Danner") 
print("   Example content we'd extract:")
print("   'Looking at this waveform on the oscilloscope, you can")
print("   see the injector pulse width is 2.8 milliseconds but")
print("   the current ramp shows high resistance...'")
print()
print("3. FarmCraft101")
print("   Example content we'd extract:")
print("   'This Kubota tractor won't move forward. The hydraulic")
print("   filter part number 15741-63010 was completely clogged.")
print("   After replacing it, full hydraulic pressure restored...'")
print()
print("4. Bobcat Company")
print("   Example content we'd extract:")
print("   'To perform the 500 hour service on your S740, you'll")
print("   need hydraulic filter 7023037, engine oil filter 7012303")
print("   and 15W-40 oil. Start by...'")
print()
print("=" * 60)
print("🔍 WHAT WE EXTRACT FROM THE TRANSCRIPTS:")
print()
print("ERROR CODES:")
print("  P0171 - System too lean bank 1")
print("  P0300 - Random misfire")
print("  C1234 - ABS sensor fault")
print()
print("PART NUMBERS:")
print("  7023037 - Bobcat hydraulic filter")
print("  15741-63010 - Kubota hydraulic filter")
print("  13627588988 - BMW O2 sensor")
print()
print("TOOLS MENTIONED:")
print("  • Scan tool")
print("  • Multimeter")
print("  • Oscilloscope")
print("  • Fuel pressure gauge")
print()
print("PROBLEMS:")
print("  • Won't start")
print("  • Rough idle")
print("  • No hydraulic pressure")
print("  • DPF regeneration issues")
print()
print("SOLUTIONS:")
print("  • Replaced clogged filter")
print("  • Cleaned MAF sensor")
print("  • Adjusted valve clearance")
print("  • Performed forced regen")
print()
print("=" * 60)
print("💾 STORAGE:")
print()
print("All this knowledge goes into BigQuery tables:")
print("  • youtube_equipment.transcripts")
print("  • youtube_equipment.channel_knowledge")
print()
print("Bob's Brain can then query this to answer questions like:")
print("  'How do I fix P0171 on a Ford?'")
print("  'What's the part number for Bobcat S740 hydraulic filter?'")
print("  'How do I test a fuel injector with an oscilloscope?'")
print()
print("🚀 READY TO RUN!")
print("The scraper is configured with your channels.")
print("It will extract transcripts and build your knowledge base!")