name: 💡 Feature Request
description: Suggest a new feature for Bob's Brain
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like Bob to be able to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - AI/ML Enhancement
        - Data Collection
        - Slack Integration
        - Performance
        - Security
        - DevOps/Infrastructure
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (important for productivity)
        - Critical (blocking current work)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches might include...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: This could be implemented by...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Feature X works as expected
        - [ ] Documentation is updated
        - [ ] Tests are added
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Screenshots, diagrams, related issues, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: This feature aligns with Bob's Brain goals
          required: true