name: ❓ Question
description: Ask a question about Bob's Brain
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! 🤔

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about Bob's Brain?
      placeholder: How do I...? What is...? Why does...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: Which area is your question about?
      options:
        - Setup/Installation
        - Configuration
        - Usage/Features
        - Troubleshooting
        - Development
        - Architecture
        - Deployment
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your question
      placeholder: I'm trying to... and I expected... but instead...

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted to solve this?
      placeholder: I tried... I looked at... I searched for...

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Provide environment details if relevant to your question
      value: |
        - OS: [e.g. Ubuntu 20.04]
        - Python version: [e.g. 3.11.2]
        - Bob's Brain version: [e.g. main branch]
      render: markdown

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and documentation
          required: true
        - label: I have provided sufficient context for my question
          required: true