# GitHub Pages Configuration for Bob's Brain Documentation

# Site settings
title: "Bob's Brain - AI Assistant Ecosystem"
description: "Intelligent AI assistant ecosystem with multiple specialized branches for different use cases"
baseurl: ""
url: "https://jeremylongshore.github.io/bobs-brain"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Branch Guide"
    url: "/BRANCH_GUIDE"
  - title: "Contributing"
    url: "/CONTRIBUTING"
  - title: "GitHub"
    url: "https://github.com/jeremylongshore/bobs-brain"

# Social links
github_username: jeremylongshore
repository: "jeremylongshore/bobs-brain"

# SEO
lang: "en-US"
author: "Jeremy Longshore"

# Enable Mermaid diagrams
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "page"