name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make ci-install

    - name: Run tests
      run: make ci-test

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from commits since last tag
        if [ $(git tag --list | wc -l) -gt 1 ]; then
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1)
          CHANGELOG=$(git log --pretty=format:"* %s (%h)" $PREV_TAG..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"* %s (%h)")
        fi
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: Bob's Brain ${{ steps.version.outputs.VERSION }}
        body: |
          ## 🧠 Bob's Brain Release ${{ steps.version.outputs.VERSION }}

          ### Changes in this release:
          ${{ steps.changelog.outputs.CHANGELOG }}

          ### 🚀 Deployment
          ```bash
          git checkout ${{ steps.version.outputs.VERSION }}
          make deploy
          ```

          ### 📊 System Health
          - ✅ All tests passing
          - ✅ Security checks passed
          - ✅ Code quality verified

          Built with ❤️ by the Bob's Brain community
        draft: false
        prerelease: false

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bobs-brain \
          --source . \
          --platform managed \
          --region us-central1 \
          --project bobs-house-ai \
          --memory 1Gi \
          --timeout 3600 \
          --min-instances 0 \
          --max-instances 10